### ISSUE TITLE
ImportError issue

### ISSUE THREAD

**Issue by Esteban795** [sebastiengiordano/OC__DA_Python_P4#1]
Bonjour,

Mon professeur de NSI m'a fait parvenir le lien de ce repo afin d'avoir une idée de comment pourrait fonctionner un gestionnaire de tournoi. 
Lors de l'exécution de "__main__.py", on obtient : "ImportError: attempted relative import with no known parent package". 
Exemple : on se trouve dans le dossier "controllers", fichier :  "main_controllers.py". Lors de l'importatiopn des packages quand on lance "__main__.py", le chemin relatif pour accéder aux autres fichiers n'est pas par rapport à "main_controllers.py" mais par rapport à "__main__.py". J'ai donc modifié le chemin relatif en local pour accéder aux packages, et tout fonctionne de mon côté. 

En espérant avoir pu aider,
Esteban.

![issue](https://user-images.githubusercontent.com/58440121/110905569-f3e95980-830a-11eb-9bdd-f03491d1cbee.png)

**Comment by sebastiengiordano** [comment]
Bonjour,
Merci pour ce retour. Mais en fait il n'y a pas de problème...
Tout dépend de comment est lancé ce projet. Je le lance par appel de module via la commande:
py -m NomDuProjet
et donc tout les import son géré en relatif par rapport à "NomDuProjet".
De plus, ce repo me permet de transmettre à mon mentor d'OpenClassRoom mon projet... Il n'est donc pas achevé. Ayant un jour de formation par semaine, il le sera sous 4 semaines environ...
Je serais heureux d'avoir votre retour à ce moement là !
Cordialement,
   Sébastien.
